module.exports.HMOList = [
  "Doc Hudson",
  "Megamind",
  "HuHot Guy",
  "Mummy Pig",
  "Pingu",
  "King Juliean",
  "Wall-E",
  "Bob the Tomato",
  "Larry the Cucumber",
  "String Theory",
  "Beetlejuice",
  "Betelgeuse",
  "🫃",
  "Larry Ellison",
  "Undercover Mater",
  "Ur Mom",
  "Lord Farquad",
  "Principle Skinner",
  "Tinky Winky",
  "Subway Surfers Cop",
  "Clippy",
  ":O",
  "Burger King",
  "Wendy",
  "Big the Cat",
  "Ronald McDonald",
  "Margret Thatcher",
  "Jeffrey Epstein (I can fix him)",
  "Lace",
  "Crul and Benjin",
  "Zote",
  "8",
  "Plastic Dinosaur",
  "Just Dance Silhouette",
  "backyardigans penguin",
  "zoboomafoo",
  "Chris Kratt",
  "🦧",
  "William Howard Taft",
  "Alfred Nobel",
  "Northern Lion",
  "Agent 47",
  "Abomasnow",
  "Default Woman Mii",
  "The Shower Drain",
  "Robbin Willams from the hit movie flubber",
  "Flubber from the hit movie Robbin Willams",
  "Alf",
  "Tootsie Roll with a razor in it",
  "*",
  "<@1393814433473757255>",
  "Wumpus",
  "Among Us bobby",
  "Lego BatMan",
  "REV ROBOTICS©: SparkMax",
  "Hole in wall",
  "The concept of having a secure future",
  "Glorbo",
  "Sharktales Blueray DVD",
  "gravity",
  "blue",
  "github dude",
  "thanxgiving turkey",
  "Grunkle Stan",
  "Rocktopus",
  "NOT OPAMA",
  "Paper Crane",
  "page 23 of the Great Gatsby",
  "The mongolian subtitles of Stranger Things",
];
