module.exports.HMOList = [
  "Doc Hudson",
  "Megamind",
  "HuHot Guy",
  "Mummy Pig",
  "Pingu",
  "King Juliean",
  "Wall-E",
  "Bob the Tomato",
  "Larry the Cucumber",
  "String Theory",
  "Beetlejuice",
  "Betelgeuse",
  "🫃",
  "Larry Ellison",
  "Undercover Mater",
  "Ur Mom",
  "Lord Farquad",
  "Principle Skinner",
  "Tinky Winky",
  "Subway Surfers Cop",
  "Clippy",
  ":O",
  "Burger King",
  "Wendy",
  "Big the Cat",
  "Ronald McDonald",
  "Margret Thatcher",
  "Jeffrey Epstein (I can fix him)",
  "Lace",
  "Crul and Benjin",
  "Zote",
  "8",
  "Plastic Dinosaur",
  "Just Dance Silhouette",
  "backyardigans penguin",
  "zoboomafoo",
  "Chris Kratt",
  "🦧",
  "William Howard Taft",
  "Alfred Nobel",
  "Northern Lion",
  "Agent 47",
  "Abomasnow",
];
