module.exports.LongLanguageDict = (
            { name:'Afrikaans', value: 'af' },
            { name:'Amharic', value: 'am' },
            { name:'Arabic', value: 'ar' },
            { name:'Bulgarian', value: 'bg' },
            { name:'Bislama', value: 'bi' },
            { name:'Bengali', value: 'bn' },
            { name:'Bosnian', value: 'bs' },
            { name:'Catalan', value: 'ca' },
            { name:'Czech', value: 'cs' },
            { name:'Welsh', value: 'cy' },
            { name:'Danish', value: 'da' },
            { name:'German', value: 'de' },
            { name:'Greek', value: 'el' },
            { name:'English', value: 'en'},
            { name:'Spanish', value: 'es' },
            { name:'Estonian', value: 'et' },
            { name:'Basque', value: 'eu' },
            { name:'Finnish', value: 'fi' },
            { name:'French', value: 'fr' },
            { name:'Galician', value: 'gl' },
            { name:'Gujarati', value: 'gu' },
            { name:'Hausa', value: 'ha' },
            { name:'Hebrew', value: 'he' },
            { name:'Hindi', value: 'hi' },
            { name:'Croatian', value: 'hr' },
            { name:'Hungarian', value: 'hu' },
            { name:'Indonesian', value: 'id' },
            { name:'Icelandic', value: 'is' },
            { name:'Italian', value: 'it' },
            { name:'Japanase', value: 'ja' },
            { name:'Javanese', value: 'jv' },
            { name:'Khmer', value: 'km' },
            { name:'Kannada', value: 'kn' },
            { name:'Korean', value: 'ko' },
            { name:'Malay', value: 'ms' },
            { name:'Burmese', value: 'my' },
            { name:'Nepali', value: 'ne' },
            { name:'Dutch', value: 'nl' },
            { name:'Norwegian', value: 'no' },
            { name:'Punjabi', value: 'pa' },
            { name:'Polish', value: 'pl' },
            { name:'Portuguese', value: 'pt' },
            { name:'Romanian', value: 'ro' },
            { name:'Russian', value: 'ru' },
            { name:'Sinhala', value: 'si' },
            { name:'Slovak', value: 'sk' },
            { name:'Albanian', value: 'sq' },
            { name:'Serbian', value: 'sr' },
            { name:'Sudanese', value: 'su' },
            { name:'Swedish', value: 'sv' },
            { name:'Swahili', value: 'sw' },
            { name:'Tamil', value: 'ta' },
            { name:'Telugu', value: 'te' },
            { name:'Thai', value: 'th' },
            { name:'Turkish', value: 'tr' },
            { name:'Ukranian', value: 'uk' },
            { name:'Urdu', value: 'ur' },
            { name:'Vietnamese', value: 'vi' },
            { name:'Chinese', value: 'zh' }
)

module.exports.LongLanguageArray = [
            'af',
            'am',
            'ar',
            'bg',
            'bi',
            'bn',
            'bs',
            'ca',
            'cs',
            'cy',
            'da',
            'de',
            'el',
            'en',
            'es',
            'et',
            'eu',
            'fi',
            'fr',
            'gl',
            'gu',
            'ha',
            'he',
            'hi',
            'hr',
            'hu',
            'id',
            'is',
            'it',
            'ja',
            'jv',
            'km',
            'kn',
            'ko',
            'ms',
            'my',
            'ne',
            'nl',
            'no',
            'pa',
            'pl',
            'pt',
            'ro',
            'ru',
            'si',
            'sk',
            'sq',
            'sr',
            'su',
            'sv',
            'sw',
            'ta',
            'te',
            'th',
            'tr',
            'uk',
            'ur',
            'vi',
            'zh'
]
